### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by conneralegre** [bartius-nigel/capstone-project-2-expresso#2]
Simplify - I recommend using a style guide to format your code in a way that improves the readability and organization.

We can make improvements to the indentation and spacing by following a javascript style guide like this one from airbnb: https://github.com/airbnb/javascript

Alternatively, this one from Google: https://google.github.io/styleguide/jsguide.html

**Comment by bartius-nigel** [comment]
That is so cool Conner! Thanks, that ESLint was also equally cool and will be using that in all my projects now
